#!/bin/bash
# Desarrollado por Pablo Guerrero
# Para el amor de mi vida, mi Chalipanga. Sin ella no soy nada.
# Versión 1 Licencia GPL v 3.0
# Esta Script usa las herramientas wget y csvkit y herramientas estándar de Linux (grep,tee,echo,sed)
#
### 1. Creación de variables
PRTGAUTH="username=pguerrero&passhash=115204423"
URL="https://10.13.60.250/api/table.xml?content=devices&columns=host,device,objid,tags&$PRTGAUTH&output=csvtable&count=99999999"
### 2. Descarga de sensores
wget --no-check-certificate -qO- $URL > full.csv;ALL=full.csv
### 3. Separación de sensores: Cámaras, botones, switches, pmis
TARGET=$(grep -e '172.17' -e '172.23' -e '10.1.' -e '172.18' -e '172.19' -e '172.16' < $ALL |grep -v '10.13'|csvcut -c 1 |sort|uniq -D)
#TARGET=$(csvcut -c 1 < $ALL|sort|uniq -D)
echo "$TARGET" | tee tmp.csv; csvgrep -c 1 -f tmp.csv < $ALL |csvcut -c 1,3,5,7 > SensoresDuplicadosIDyTag.csv
#FULL=$(csvcut -c 1,3 < $ALL)
rm -rf full.csv tmp.csv
