#!/bin/bash
# Desarrollado por Pablo Guerrero
# Para el amor de mi vida, mi Chalipanga. Sin ella no soy nada.
# Versión 1.1 Licencia GPL v 3.0
# Esta Script usa las herramientas wget y csvkit y herramientas estándar de Linux (grep,tee,echo,sed)
#
# USO: ./TagUpdater2_specific GROUPID
### 1. Creación de variables
PRTGAUTH="username=pguerrero&passhash=115204423"
GURL="https://10.13.60.250/api/table.xml?content=groups&columns=group,objid&$PRTGAUTH&output=csvtable&count=99999999"
DURL="https://10.13.60.250/api/table.xml?content=devices&columns=host,objid,group&$PRTGAUTH&output=csvtable&count=99999999"
### 1.1 Tags de sensores
TAG=""
GID=$1
### 1. Descarga de sensores
wget --no-check-certificate -qO- $GURL > groups.csv;
wget --no-check-certificate -qO- $DURL > full.csv;
DEVS=full.csv; GRPS=groups.csv
### 2. Separación de sensores
GNAME=$(csvgrep -r $GID -c 3 < $GRPS | csvcut -c 1 -K 1)
GSENSORS=$(csvgrep -r "$GNAME" -c 5 < $DEVS |csvcut -c 1,3 -K 1)
### 3. Etiquetado
echo -e "PRTG Etiquetado Masivo de Dispositivos Grupo: $GROUP\n$(date) \nbatts & z64 with ♥\n==================================\nID\tDispositivo\tStatus" | tee -a log
echo "$GSENSORS" > tmp.csv; while IFS=',' read ip id; do echo -n -e "\n$ip\t$id\t> " |tee -a log ; wget --no-check-certificate -qO- "https://10.13.60.250/api/setobjectproperty.htm?id=$id&name=tags&value=$TAG&$PRTGAUTH"|sed -e 's/<[^>]*>//g' | tee -a log ; done < tmp.csv;
echo -e "Proceso Finalizado\n$(date +%D-%T-Hrs)\n" | tee -a log
